name: CI for Docker Compose and Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-compose:
    name: Test Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        uses: docker://docker/compose:latest
        with:
          entrypoint: /bin/sh
          args: |
            -c "docker-compose up -d --build && docker-compose ps"

      - name: Tear down Docker Compose
        if: always()
        uses: docker://docker/compose:latest
        with:
          entrypoint: /bin/sh
          args: docker-compose down

  terraform:
    name: Test Terraform
    runs-on: ubuntu-latest
    needs: docker-compose

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Terraform Init, Validate, Plan, and Apply
        uses: docker://hashicorp/terraform:1.9.2
        with:
          entrypoint: /bin/sh
          args: |
            -c "
            terraform init &&
            terraform validate &&
            terraform plan &&
            terraform apply -auto-approve -input=false -lock=false -no-color
            "
