name: CI for Docker Compose and Terraform

on:
  push:
    branches:
      - main
    paths:
      - Projets/Template/SFTPGo/**
      - .github/workflows/sftpgo-ci.yml

  pull_request:
    branches:
      - main
    paths:
      - Projets/Template/SFTPGo/**
      - .github/workflows/sftpgo-ci.yml

jobs:
  docker-compose:
    name: Test Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build and run Docker Compose
        run: |
          docker compose -f Projets/Template/SFTPGo/docker-compose.yml up -d --build
          
      - name: Verify services are running
        run: docker compose -f Projets/Template/SFTPGo/docker-compose.yml ps

      - name: Tear down Docker Compose
        if: always()
        run: docker compose -f Projets/Template/SFTPGo/docker-compose.yml down

  terraform:
    name: Test Terraform
    runs-on: ubuntu-latest
    needs: docker-compose

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Terraform Init
        run: |
          docker run --rm -v "${{ github.workspace }}/Projets/Template/SFTPGo/Terraform config:/workspace" -w /workspace hashicorp/terraform:1.9.2 init

      - name: Terraform Validate
        run: |
          docker run --rm -v "${{ github.workspace }}/Projets/Template/SFTPGo/Terraform config:/workspace" -w /workspace hashicorp/terraform:1.9.2 validate

      - name: Terraform Plan
        run: |
          docker run --rm -v "${{ github.workspace }}/Projets/Template/SFTPGo/Terraform config:/workspace" -w /workspace hashicorp/terraform:1.9.2 plan